language: rust
sudo: false
dist: trusty

cache:
  cargo: true
  apt: true

matrix:
  include:
    - rust: stable
    - rust: beta
    - rust: nightly
  allow_failures:
    - rust: nightly

before_script:
  - |
    if [[ "$TRAVIS_RUST_VERSION" != "nightly" ]]; then
      rustup component add rustfmt
    fi

script:
  - |
    if [[ "$TRAVIS_RUST_VERSION" != "nightly" ]]; then
      cargo fmt -- --check
    fi
  - cargo check --all --no-default-features
  - cargo test --all-features --all -- --nocapture
